---
- set_fact:
    interface_name: "{{ cloud_instance_item.name }}_{{ cloud_interface_item.name }}"

- name: Create Azure NIC {{ interface_name }} for {{ cloud_instance_item.name }} in {{ cloud_vpc_data.region }}
  azure_rm_networkinterface:
    name: "{{ interface_name }}"
    resource_group: "{{ cloud_vpc_name }}"
    virtual_network_name: "{{ cloud_vpc_name }}_vnet"
    subnet_name: "{{ cloud_interface_item.subnet }}"
    private_ip_address: "{{ cloud_interface_item.private_ip_cidr | ipaddr('address') if cloud_interface_item.private_ip_cidr is defined else omit }}"
    private_ip_allocation_method: "{{ 'Static' if cloud_interface_item.private_ip_cidr is defined else omit }}"
    security_group_name: "{{ cloud_interface_item.acl | default(omit) }}"
    # public_ip_address_name: publicip001
  register: nic_results

- debug: var=nic_results

- set_fact:
    network_interface_list: "{{ network_interface_list + [ interface_name ] }}"

- block:
    - name: Create routes
      azure_rm_deployment:
        deployment_mode: incremental
        wait_for_deployment_completion: yes
        state: present
        location: "{{ cloud_vpc_data.region }}"
        resource_group_name: "{{ cloud_vpc_name }}"
        template:
          $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
          contentVersion: "1.0.0.0"
          resources:
            -
              type: 'Microsoft.Network/routeTables"'
              name: "{{ cloud_interface_item.subnet }}"
              apiVersion: '2017-10-01'
              properties:
                routes:
                  -
                    name: "{{ cloud_instance_item.name }}"
                    properties:
                      addressPrefix: '0.0.0.0/0'
                      nextHopType: 'VirtualAppliance'
                      nextHopIpAddress: "{{ nic_results.state.ip_configuration.private_ip_address }}"
                subnets:
                  -
                    name: "{{ cloud_interface_item.subnet }}"
                    properties:
                      # addressPrefix: '{{ cloud_info["azure"].outside_cidr }}'
                      routeTable:
                        id: "[resourceId('Microsoft.Network/routeTables', {{ cloud_instance_item.name }})]"
  when: cloud_interface_item.gateway | default('false') | bool
