---
- hosts: rtr1.hub
  connection: local
  gather_facts: false

  tasks:
    - name: show ospf neighbors
      ios_command:
        commands: 'show ip ospf neighbor'
      register: ospf

    - name: show ip route
      ios_command:
        commands: 'show ip route ospf'
      register: routes

    - name: show dmvpn neighbors
      ios_command:
        commands: 'show dmvpn'
      register: dmvpn

    - debug:
        msg: "{{dmvpn.stdout[0].split('\n')[9,15]}}"

    # - name: ping site
    #   net_ping:
    #     dest: "{{new_site | default('10.0.253.254')}}"
    #   register: ping
    #
    # - debug:
    #     msg: "{{ospf.stdout_lines}}"
    #
    # - debug:
    #     msg: "{{routes}}"
    #
    # - debug:
    #     msg:
    #       - 'Pinging new site IP of: {{new_site}}'
    #       - 'Packets transmitted: {{ping.packets_tx}}'
    #       - 'Packets received: {{ping.packets_rx}}'
    #       - 'Packet loss: {{ping.packet_loss}}'
