---
- name: Get the VPC ID for {{ cloud_vpc_name }}
  ec2_vpc_net_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ cloud_vpc_data.region }}"
    filters:
      "tag:Name": "{{ cloud_vpc_name }}"
  register: vpc_net_facts

- block:
  - name: Set VPC ID
    set_fact:
      vpc_id: "{{ vpc_net_facts.vpcs[0].id }}"
    failed_when: vpc_net_facts.vpcs[0] is not defined

  - name: Destroy security group for project {{ cloud_vpc_data.project }} in {{ cloud_vpc_data.region }}
    ec2_group:
      aws_access_key: "{{ aws_access_key | default(omit) }}"
      aws_secret_key: "{{ aws_secret_key | default(omit) }}"
      name: "{{ cloud_security_group_item }}"
      region: "{{ cloud_vpc_data.region }}"
      state: absent
      vpc_id: "{{ vpc_id }}"
    with_items: "{{ cloud_security_group_data.keys() | default([]) }}"
    loop_control:
      loop_var: cloud_security_group_item
  when: vpc_net_facts.vpcs
