---
- name: Get the VPC ID for {{ cloud_vpc_name }}
  ec2_vpc_net_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ cloud_vpc_data.region }}"
    filters:
      "tag:Name": "{{ cloud_vpc_name }}"
  register: vpc_net_facts

- name: Set VPC ID
  set_fact:
    vpc_id: "{{ vpc_net_facts.vpcs[0].id }}"
  failed_when: vpc_net_facts.vpcs[0] is not defined

- include: "{{ role_path }}/tasks/aws-security-group.yml cloud_security_group_name={{ cloud_security_group_item }} cloud_security_group_list={{ cloud_security_group_data[cloud_security_group_item] }}"
  with_items: "{{ cloud_security_group_data.keys() | default([]) }}"
  loop_control:
    loop_var: cloud_security_group_item
