---
- include: "{{ role_path }}/tasks/os-security-group-rule.yml"
  with_items: "{{ cloud_security_group_list | default([]) }}"
  loop_control:
    loop_var: cloud_security_group_rule
  tags:
    - security_groups