---
- name: Deference the instance facts
  set_fact:
    instance_interfaces: []
    primary_interface: "{{ cloud_instance_item.name.split('.')[0] }}.0"
    instance_groups: "{{ cloud_instance_item.tags.groups | regex_replace('\\s*', '') }}"

- include_tasks: "azure-interface.yml"
  with_indexed_items: "{{ cloud_instance_item.interfaces | default([]) }}"
  loop_control:
    loop_var: cloud_interface_item

- name: Set the IP address for the instance
  set_fact:
    instance_ip_address: "{{ public_ip_map[primary_interface] | default(private_ip_map[primary_interface], true) }}"
    instance_group_list: "{{ instance_groups.split(',')|default([]) + [ cloud_name ] }}"
    instance_name: "{{ cloud_instance_item.name.split('.')[0] }}.{{ cloud_instance }}"

- name: Add ansible_network_os group for network elements
  set_fact:
    instance_group_list: "{{ instance_group_list + [ cloud_instance_item.tags.network_os ] }}"
  when: cloud_instance_item.tags.network_os is defined

- name: Add host to inventory
  add_host:
    hostname: "{{ instance_name }}"
    ansible_host: "{{ public_ip_map[primary_interface] | default(private_ip_map[primary_interface], true) }}"
    ansible_user: "{{ cloud_instance_item.ansible_user | default(cloud_user) }}"
    groups: "{{ cloud_instance_item.tags.groups | default(omit) }}"
    ansible_network_os: "{{ cloud_instance_item.tags.network_os | default('') }}"
    private_ip_address: "{{ private_ip_map[primary_interface] }}"
    interfaces: "{{ instance_interfaces }}"
    cloud_template_item: "{{ cloud_instance_item }}"
    cloud_vpc_data: "{{ cloud_vpc_data }}"

- name: Create inventory host entry
  set_fact:
    host_entry:
      hostname: "{{ instance_name }}"
      ansible_host: "{{ public_ip_map[primary_interface] | default(private_ip_map[primary_interface], true) }}"
      ansible_user: "{{ cloud_instance_item.ansible_user | default(cloud_user) }}"
      groups: "{{ cloud_instance_item.tags.groups | default(omit) }}"
      ansible_network_os: "{{ cloud_instance_item.tags.network_os | default('') }}"
      private_ip_address: "{{ private_ip_map[primary_interface] }}"
      interfaces: "{{ instance_interfaces }}"

- name: Add host entry to the host_interfaces_dict
  set_fact:
      host_interfaces_dict: "{{ host_interfaces_dict | combine({ instance_name: instance_interfaces }) }}"

- name: Add host entry to the host_inventory_dict
  set_fact:
      host_inventory_dict: "{{ host_inventory_dict | combine({ instance_name: host_entry }) }}"

- debug: var=instance_group_list

- name: Add host entry to the group_inventory_dict
  set_fact:
      group_inventory_dict: "{{ group_inventory_dict | combine({ group_item: [instance_name] + group_inventory_dict[group_item]|default([]) }) }}"
  with_items: "{{ instance_group_list }}"
  loop_control:
    loop_var: group_item

- debug: var=group_inventory_dict
